// Interface automatically generated by schemas-to-ts

export interface CenteredSection {
  content?: string;
}
export interface CenteredSection_Plain {
  content?: string;
}

export interface CenteredSection_NoRelations {
  content?: string;
}

