// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface SliderSection {
  title?: string;
  carousel?: { data: Media[] };
}
export interface SliderSection_Plain {
  title?: string;
  carousel?: Media[];
}

export interface SliderSection_NoRelations {
  title?: string;
  carousel?: number[];
}

