// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface SplittedSection {
  Image?: { data: Media };
  reversed?: boolean;
  Content?: string;
}
export interface SplittedSection_Plain {
  Image?: Media;
  reversed?: boolean;
  Content?: string;
}

export interface SplittedSection_NoRelations {
  Image?: number;
  reversed?: boolean;
  Content?: string;
}

