// Interface automatically generated by schemas-to-ts

export interface Section {
  title_prout_coucoucoucou?: string;
}
export interface Section_Plain {
  title_prout_coucoucoucou?: string;
}

export interface Section_NoRelations {
  title_prout_coucoucoucou?: string;
}

