// Interface automatically generated by schemas-to-ts

import { Media } from '../../../common/schemas-to-ts/Media';

export interface Test {
  test_image?: { data: Media[] };
}
export interface Test_Plain {
  test_image?: Media[];
}

export interface Test_NoRelations {
  test_image?: number[];
}

