// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Section } from '../../../../components/product/interfaces/Section';
import { Section_Plain } from '../../../../components/product/interfaces/Section';
import { Section_NoRelations } from '../../../../components/product/interfaces/Section';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Product {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    thumbnail: { data: Media };
    description: any;
    tets: Section[];
    dynamic?: any;
  };
}
export interface Product_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  thumbnail: Media;
  description: any;
  tets: Section_Plain[];
  dynamic?: any;
}

export interface Product_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  thumbnail: number;
  description: any;
  tets: Section_NoRelations[];
  dynamic?: any;
}

export interface Product_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  thumbnail: AdminPanelRelationPropertyModification<Media>;
  description: any;
  tets: Section_Plain[];
  dynamic?: any;
}
