// Interface automatically generated by schemas-to-ts

export interface Home {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    sections?: any;
    textTest?: string;
    locale: string;
    localizations?: { data: Home[] };
  };
}
export interface Home_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  sections?: any;
  textTest?: string;
  locale: string;
  localizations?: Home[];
}

export interface Home_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  sections?: any;
  textTest?: string;
  locale: string;
  localizations?: Home[];
}

export interface Home_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  sections?: any;
  textTest?: string;
  locale: string;
  localizations?: Home[];
}
